#!/usr/bin/env bash
# script configuress nginx on a server

echo "server {
    listen 80;
    location / {
        return 200 'Hello World!\n';
    }
}" > /etc/nginx/sites-available/default
nginx -s reload
