#!/usr/bin/env bash
# script configuress nginx on a server

apt-get update
apt-get install -y nginx

mkdir /etc/nginx/html
touch /etc/nginx/html/index.html

echo "Hello World!" > /var/www/html/index.nginx-debian.html
nginx -s reload
