#!/usr/bin/env bash
# script configuress nginx on a server

sudo apt-get update
sudo apt-get install -y nginx

sudo mkdir /etc/nginx/html
sudo touch /etc/nginx/html/index.html

echo "Hello World!" > /etc/nginx/html/index.html
nginx -s reload
