#!/usr/bin/env bash
# script configuress nginx on a server

apt update
apt install -y nginx

mkdir /etc/nginx/html
touch /etc/nginx/html/custom_404.html

echo "Ceci n'est pas une page" > /etc/nginx/html/custom_404.html
printf %s "server {
     listen      80 default_server;
     listen      [::]:80 default_server;
     root        /etc/nginx/html;
     index       index.html index.htm;
     
     error_page 404 /custom_404.html;
     location = /custom_404.html {
        root /etc/nginx/html;
        internal;
     }
}
" > /etc/nginx/sites-available/default
service nginx restart
