#!/usr/bin/env bash
# script configuress nginx on a server

apt update
apt install -y nginx

mkdir /etc/nginx/html
touch /etc/nginx/html/index.html

echo "Hello World!" > /etc/nginx/html/index.html
printf %s "server {
     listen      80 default_server;
     listen      [::]:80 default_server;
     root        /etc/nginx/html;
     index       index.html index.htm;
     
     error_page 404 /custom_404
     location = /custom_404 {
        return 404 'Ceci n'est pas une page';
        internal;
     }
}
" > /etc/nginx/sites-available/default
service nginx restart
