#!/usr/bin/env bash
# Installs and configure HAproxy on your lb-01 server

apt-get install -y software-properties-common
add-apt-repository ppa:vbernat/haproxy-2.8
apt-get update
apt-get install haproxy=2.8.\*

echo "ENABLED=1" >> /etc/default/haproxy
mv /etc/haproxy/haproxy.cfg{,.original}
touch /etc/haproxy/haproxy.cfg

printf %s "global
    log 127.0.0.1 local0 notice
    maxconn 2000
    user haproxy
    group haproxy

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    retries 3
    option redispatch
    timeout connect  5000
    timeout client  10000
    timeout server  10000

listen hbnb
    bind 0.0.0.0:80
    mode http
    stats enable
    stats uri /haproxy?stats
    balance roundrobin
    option httpclose
    option forwardfor
    server 264256-web-01 35.175.64.13:80 check
    server 264256-web-02 100.25.190.190:80 check
" >> /etc/haproxy/haproxy.cfg

service haproxy restart
