#!/usr/bin/env bash
# script prints Best School 10 times using while loop
n=0
while [ $n -lt 10 ];
do
if [ $n == 9 ];then
  echo "Hi"
  echo "Best School"
else
  echo "Best School"
fi
  ((n=n+1))
done
