#!/usr/bin/env bash
# script prints Best School using while loop
n=1
while [ $n -lt 11 ];
do
if [ $n == 4 ];then
  echo "bad luck"
elif [ $n == 8 ]; then
  echo "good luck"
else
  echo "Best School"
fi
  ((n=n+1))
done
