#!/usr/bin/env bash
# script prints Best School using while loop
n=1
while [ $n -lt 21 ];
do
echo $n
case $n in
  4)
    echo "bad luck from China"
    ;;

  9)
    echo "bad luck from Japan"
    ;;

  17)
    echo "bad luck from Italy"
    ;;

  *)
esac
  ((n=n+1))
done
