#!/usr/bin/env bash
# script blocks all incoming traffic, except
# ports 22, 443, 80

sudo ufw --dry-run default deny incoming

sudo ufw --dry-run allow ssh

sudo ufw --dry-run allow http

sudo ufw --dry-run allow https

sudo ufw --dry-run enable
