#!/usr/bin/env bash
# script configures ubuntu server; localhost resolves to 127.0.0.2, facebook.com resolves to 8.8.8.8
cp /etc/hosts ~/hosts.latest
sed -i 's/127.0.0.1/127.0.0.2/' ~/hosts.latest
sed -i -e '$a8.8.8.8 facebook.com' ~/hosts.latest
cp -f ~/hosts.latest /etc/hosts
